### ISSUE TITLE
Box2d example?

### ISSUE THREAD

**Issue by bradparks** [Beeblerox/Simplest-Heaps-Examples#1]
Hey! Thanks for these examples... I'm new to this, and just started trying to use VS Code, Heaps and Haxe. I can run some of the examples, but when I tried to run the Box2d one, and get this when trying to run it against JS target or HeapsHL target.

```> Executing task: haxe --connect 6000 game_hl.hxml <

/Users/bparks/gitrepos/haxelib/box2d/1,2,3/box2D/dynamics/B2DebugDraw.hx:25: characters 7-27 : You cannot access the flash package while targeting hl (for flash.display.Sprite)
/Users/bparks/gitrepos/haxelib/box2d/1,2,3/box2D/dynamics/controllers/B2Controller.hx:23: characters 7-33 :     referenced here
/Users/bparks/gitrepos/haxelib/box2d/1,2,3/box2D/dynamics/B2World.hx:40: characters 7-46 :     referenced here
Game.hx:1: characters 7-29 :     referenced here
The terminal process terminated with exit code: 1```

**Comment by Beeblerox** [comment]
@bradparks sorry for not answering earlier. i'll fix this issue tomorrow
there must be something wrong with compiler conditionals in box2d

**Comment by Beeblerox** [comment]
you need to use box2d lib installed not from haxelib, but from github:
`haxelib git box2d https://github.com/openfl/box2d.git`
(gihub version have compatibilty fixes with other frameworks)

**Comment by Beeblerox** [comment]
@bradparks have you used version of box2d from git?

**Comment by bradparks** [comment]
hey! sorry I didn't report back - that fixed it! much appreciated!
